# Generated by Django 3.2.9 on 2021-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Davido', 'Davido'), ('Wizkid', 'Wizkid'), ('Drake', 'Drake'), ('JBeiber', 'JBeiber')], max_length=128, unique=True, verbose_name='category')),
                ('description', models.CharField(max_length=350)),
                ('blob', models.DecimalField(decimal_places=2, max_digits=3)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
