# Generated by Django 3.2.9 on 2021-12-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Davido', 'Davido'), ('Wizkid', 'Wizkid'), ('Drake', 'Drake'), ('JBeiber', 'JBeiber')], max_length=128, verbose_name='category'),
        ),
    ]
