# Generated by Django 3.2.9 on 2021-12-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonapp', '0003_post_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, default='static/skull.png', null=True, upload_to=''),
        ),
    ]
