# Generated by Django 3.2.9 on 2021-12-21 14:39

import anonapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonapp', '0004_alter_post_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='post',
            name='banner_image_url',
            field=models.URLField(default=anonapp.models.choice, help_text='Provide a banner image for your post'),
        ),
    ]
